name: "Hello World"
description: "A simple action that says hello"
inputs:
  name:
    description: "Name to say hello to"
    default: "world"
outputs:
  message:
    description: "The message that the action outputs"
runs:
  using: "bash"
  main: "entrypoint.sh"
