name: Hello World Workflow
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      uses: mounesi/test@master
      with:
        name: "Alire M"
    - name: my-step
      run: echo "Hello World!"
